# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://konnor-filip.github.io/Learn2Surf/
title: Learn2Surf
email: your-email@domain.com
author: Octavio Munoz Reynoso and Konnor Filip
description: > # "Write an awesome description for your new site here. 
  Learn2Surf is a Capstone project with the goal of creating lesson plans for teachers. The goal of the project is to inform students about cybersecurity, prepare them for some of the challeneges they might encounter in the real world and develop educational content on how they can beat those challenges. 
copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/Konnor-Filip/Learn2Surf
